// Generated by CoffeeScript 1.12.4
var Service, registry, serv;

registry = Object.create(null);

Service = require("./Service");

serv = function(serviceId) {
  return registry[serviceId];
};

serv.set = function(serviceId, config) {
  return registry[serviceId] = Service(config);
};

serv.del = function(serviceId) {
  return delete registry[serviceId];
};

module.exports = serv;
