// Generated by CoffeeScript 1.12.4
var Service, registry, serv;

registry = Object.create(null);

Service = require("./Service");

serv = function(name) {
  return registry[name];
};

serv.set = function(name, config) {
  if (config === null) {
    return delete registry[name];
  } else {
    return registry[name] = Service(name, config);
  }
};

module.exports = serv;
